name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile C++ code
      run: g++ -o hospital_management hospital_management.cpp

    - name: Run program (optional)
      run: ./hospital_management
